name: Deploy Showcases

on:
  push:
    branches:
      - formula-editor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
           npm install

    - name: Build 
      run: |
        npm run build

    - name: Deploy formula-editor
      run: |
        mkdir -p deployment/formula-editor
        cp -r showcase/formula-editor/dist/* deployment/formula-editor/

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: deployment
